### ISSUE TITLE
Configuration window

### ISSUE THREAD

**Issue by Sawair** [Toumash/daily-status#11]
Add option to manage config from app (UI version)

**Comment by Sawair** [comment]
Add month hour target as an alternative to WorkDay config, then calculate the time needed per day to accomplish target. It's could be a good option if you are on an hourly rate and want to earn specific amount.

**Comment by Toumash** [comment]
I think that will be a good task for you @Sawair 👍

**Comment by Toumash** [comment]
I can take that task

**Comment by Toumash** [comment]
The configuration should contain the lastUsedWorkspace (Id and Name).
Then the main window can load it from this place https://github.com/Toumash/daily-status/blob/dev/DailyStatus.UI/ViewModel/StatusViewModel.cs#L265

**Comment by Toumash** [comment]
Add option to lock scale range from https://github.com/Toumash/daily-status/issues/12

**Comment by Sawair** [comment]
In lock scale range option we want only toggle button or also a value (like in Month target)?
![obraz](https://user-images.githubusercontent.com/18036211/40584807-ee522952-61a7-11e8-9de6-7b94931b32bf.png)

**Comment by Toumash** [comment]
value :)
nice design btw

**Comment by Sawair** [comment]
Ok, changes in progress, can be peep [here](https://github.com/Toumash/daily-status/tree/feature/11-configuration-window )

**Comment by Toumash** [comment]
@Sawair 18 days ago...

**Comment by Toumash** [comment]
Whats the status?

**Comment by Toumash** [comment]
Closed by #25
