### ISSUE TITLE
Overwork gauge

### ISSUE THREAD

**Issue by Toumash** [Toumash/daily-status#14]
When you do over 8 hours a day, the fill color becomes the background and the background becomes the active fill.
I've written a simple alternatingColor converter but it is not working :<
 commit 4173040

**Comment by Toumash** [comment]
@Sawair would you like to do it?

**Comment by Sawair** [comment]
Ok, I'll take a look

**Comment by Sawair** [comment]
Ok, so there is an issue in Live-Chards that can't bind GaugeActiveFill.
It's right there: [https://github.com/Live-Charts/Live-Charts/issues/796](url)

**Comment by Toumash** [comment]
a second gauge would be a good workaround

**Comment by Toumash** [comment]
redesign removes this problem

**Comment by mjanulaitis** [comment]
Still seems to be an issue,
